name: mediator
description: Simple mediator implementation in pure Dart.
version: 0.0.1
homepage: https://github.com/bytes7bytes7/mediator

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
